name: Package Source Code ZIP

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Upload source as artifact ZIP
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.repository.name }}_source
          path: |
            .
            !.git/**
            !.gradle/**
            !.idea/**
            !**/.DS_Store
            !**/build/**
            !**/captures/**
            !**/.cxx/**
            !**/.externalNativeBuild/**
            !local.properties
            !**/*.apk
            !**/*.aab
          if-no-files-found: error
